#!/bin/env bash
PROJECT_NAME=${PWD##*/}
PROJECT_DIR=${PWD}
EX_GIT=$(/usr/bin/whereis git)
EX_CURL=$(/usr/bin/whereis curl)
EX_REBAR="${PWD}/rebar"

ET_REPO="https://github.com/alxrt/et_.git"
REBAR_URL="https://github.com/rebar/rebar/wiki/rebar"

${EX_GIT} clone ${ET_REPO} ./
rm -rf .git ./et_
echo "APP ?= ${PROJECT_NAME}">>./make/vars.mk
${EX_CURL} -L -o ./rebar ${REBAR_URL}
mkdir -p ./apps/${PROJECT_NAME}/include ./rel ./deps
chmod +x ./rebar
cd ${PROJECT_DIR}/apps/${PROJECT_NAME}
${EX_REBAR} c-a appid=${PROJECT_NAME}
cd ${PROJECT_DIR}/rel
${EX_REBAR} c-n nodeid=${PROJECT_NAME}

